### ISSUE TITLE
Sample animation does not play in Firefox

### ISSUE THREAD

**Issue by QuLogic** [rgutzen/visualizing_cortical_waves#1]
In Matplotlib, we eventually figured out that pix format should be yuv420p:

https://github.com/matplotlib/matplotlib/blob/23d3d305a8cb47193700f55934348f340c16cd17/lib/matplotlib/animation.py#L564-L569

**Comment by rgutzen** [comment]
Thanks for pointing out the incompatibility. I don't fully understand the relevant encoding details here, however, I managed to make it run with Firefox by replacing the mp4 video with webm.

**Comment by QuLogic** [comment]
Yep, that works now.
